### ISSUE TITLE
segfault with an edge-case using catalogs to parse xml

### ISSUE THREAD

**Issue by Klortho** [gagern/libxmljs#8]
I just encountered a weird bug that’s causing a segfault when using oasis catalogs to parse xml. It doesn't happen in the original libxmljs, v 0.17.1. I see there are some differences between the FromXml method:
- [libxmljs - FromXml](https://github.com/polotek/libxmljs/blob/v0.17.1/src/xml_document.cc#L407)
- [libxmljs-mt - FromXml](https://github.com/gagern/libxmljs/blob/master/src/xml_document.cc#L403)

It's an edge case, but I thought you might like to know. I don't know what causes it. Running the binary `xmllint` command from the command line does not have a problem. (It correctly says the file is invalid).

Here it is as [a gist](https://gist.github.com/Klortho/fe94b65c6f116bb089db)

**Comment by gagern** [comment]
Looking at a [diff of the implementations](https://github.com/polotek/libxmljs/compare/v0.17.0...gagern:v0.17.0-mt#diff-43e31d2e181a843a34b075f5387b33efR403), the only difference in that code appears to be the error handling. So likely it's a problem there. Investigating…

**Comment by gagern** [comment]
Not the error handling, but the memory management was to blame. Thanks for the report!

**Comment by Klortho** [comment]
Quick work in fixing it, thanks! I'm curious -- what development tools do you use for this project? IDE?

**Comment by Klortho** [comment]
Also, I sent you an email to Martin...@gmx.net -- let me know if you didn't get it.

**Comment by gagern** [comment]
> what development tools do you use for this project? IDE?

Emacs and gdb. The `-d` flag to `node-gyp` goes a long way in making gdb output useful.

**Comment by Klortho** [comment]
Thanks again!
